#############################################################################
# Makefile for building: ElegantWeather
# Generated by qmake (3.1) (Qt 6.10.0)
# Project:  ElegantWeather.pro
# Template: app
# Command: /home/mlayug/Qt/6.10.0/gcc_64/bin/qmake -o Makefile ElegantWeather.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I../Qt/6.10.0/gcc_64/include -I../Qt/6.10.0/gcc_64/include/QtQuick -I../Qt/6.10.0/gcc_64/include/QtOpenGL -I../Qt/6.10.0/gcc_64/include/QtGui -I../Qt/6.10.0/gcc_64/include/QtQmlMeta -I../Qt/6.10.0/gcc_64/include/QtQmlModels -I../Qt/6.10.0/gcc_64/include/QtQmlWorkerScript -I../Qt/6.10.0/gcc_64/include/QtQml -I../Qt/6.10.0/gcc_64/include/QtQmlIntegration -I../Qt/6.10.0/gcc_64/include/QtNetwork -I../Qt/6.10.0/gcc_64/include/QtCore -I. -I../Qt/6.10.0/gcc_64/mkspecs/linux-g++
QMAKE         = /home/mlayug/Qt/6.10.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/mlayug/Qt/6.10.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/mlayug/Qt/6.10.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ElegantWeather1.0.0
DISTDIR = /home/mlayug/ElegantWeather/.tmp/ElegantWeather1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/mlayug/Qt/6.10.0/gcc_64/lib -Wl,-rpath-link,/home/mlayug/Qt/6.10.0/gcc_64/lib
LIBS          = $(SUBLIBS) /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6Quick.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6OpenGL.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6Gui.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6QmlMeta.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6QmlModels.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6QmlWorkerScript.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6Qml.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6Network.so /home/mlayug/Qt/6.10.0/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		weatherservice.cpp \
		aiagent.cpp qrc_qml.cpp \
		moc_weatherservice.cpp \
		moc_aiagent.cpp
OBJECTS       = main.o \
		weatherservice.o \
		aiagent.o \
		qrc_qml.o \
		moc_weatherservice.o \
		moc_aiagent.o
DIST          = ../Qt/6.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/6.10.0/gcc_64/mkspecs/common/unix.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/linux.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/sanitize.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/6.10.0/gcc_64/mkspecs/qconfig.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_openxr_loader.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsplatform.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssynchronizer.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dxr.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickeffects.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testinternals_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/6.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/6.10.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/6.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/toolchain.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/default_post.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/permissions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/qt.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/resources_functions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/resources.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/moc.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/file_copies.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/yacc.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/lex.prf \
		ElegantWeather.pro weatherservice.h \
		aiagent.h main.cpp \
		weatherservice.cpp \
		aiagent.cpp
QMAKE_TARGET  = ElegantWeather
DESTDIR       = 
TARGET        = ElegantWeather


first: all
####### Build rules

ElegantWeather:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ElegantWeather.pro ../Qt/6.10.0/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt/6.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/6.10.0/gcc_64/mkspecs/common/unix.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/linux.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/sanitize.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/6.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/6.10.0/gcc_64/mkspecs/qconfig.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_openxr_loader.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsplatform.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssynchronizer.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dxr.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickeffects.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testinternals_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/6.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/6.10.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/6.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/toolchain.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/default_post.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/permissions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/qt.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/resources_functions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/resources.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/moc.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/file_copies.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/yacc.prf \
		../Qt/6.10.0/gcc_64/mkspecs/features/lex.prf \
		ElegantWeather.pro \
		qml.qrc \
		../Qt/6.10.0/gcc_64/lib/libQt6Quick.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6OpenGL.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6Gui.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6QmlMeta.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6QmlModels.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6QmlWorkerScript.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6Qml.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6Network.prl \
		../Qt/6.10.0/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile ElegantWeather.pro
../Qt/6.10.0/gcc_64/mkspecs/features/spec_pre.prf:
../Qt/6.10.0/gcc_64/mkspecs/common/unix.conf:
../Qt/6.10.0/gcc_64/mkspecs/common/linux.conf:
../Qt/6.10.0/gcc_64/mkspecs/common/sanitize.conf:
../Qt/6.10.0/gcc_64/mkspecs/common/gcc-base.conf:
../Qt/6.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt/6.10.0/gcc_64/mkspecs/common/g++-base.conf:
../Qt/6.10.0/gcc_64/mkspecs/common/g++-unix.conf:
../Qt/6.10.0/gcc_64/mkspecs/qconfig.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_ext_openxr_loader.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsplatform.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsplatform_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssynchronizer.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labssynchronizer_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_png_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlformat_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3deffects.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dxr.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick3dxr_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickeffects.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimeline.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_shadertools.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_spatialaudio.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testinternals_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/6.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/6.10.0/gcc_64/mkspecs/features/qt_functions.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/qt_config.prf:
../Qt/6.10.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt/6.10.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/6.10.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/toolchain.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/default_pre.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/resolve_config.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/default_post.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/warn_on.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/permissions.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/qt.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/resources_functions.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/resources.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/moc.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/unix/opengl.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/unix/thread.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/qmake_use.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/file_copies.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/exceptions.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/yacc.prf:
../Qt/6.10.0/gcc_64/mkspecs/features/lex.prf:
ElegantWeather.pro:
qml.qrc:
../Qt/6.10.0/gcc_64/lib/libQt6Quick.prl:
../Qt/6.10.0/gcc_64/lib/libQt6OpenGL.prl:
../Qt/6.10.0/gcc_64/lib/libQt6Gui.prl:
../Qt/6.10.0/gcc_64/lib/libQt6QmlMeta.prl:
../Qt/6.10.0/gcc_64/lib/libQt6QmlModels.prl:
../Qt/6.10.0/gcc_64/lib/libQt6QmlWorkerScript.prl:
../Qt/6.10.0/gcc_64/lib/libQt6Qml.prl:
../Qt/6.10.0/gcc_64/lib/libQt6Network.prl:
../Qt/6.10.0/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ElegantWeather.pro

qmake_all: FORCE


all: Makefile ElegantWeather

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/6.10.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents weatherservice.h aiagent.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp weatherservice.cpp aiagent.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../Qt/6.10.0/gcc_64/libexec/rcc \
		SettingsDialog.qml \
		ChatDialog.qml \
		main.qml
	/home/mlayug/Qt/6.10.0/gcc_64/libexec/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt/6.10.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h ../Qt/6.10.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_weatherservice.cpp moc_aiagent.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_weatherservice.cpp moc_aiagent.cpp
moc_weatherservice.cpp: weatherservice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QObject \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversionchecks.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfiginclude.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconfig.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfigmacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreexports.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qassert.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtnoop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypes.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversion.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlogging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qflags.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qyieldcpu.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconstructormacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qexceptionhandling.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qforeach.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttypetraits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qminmax.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnumeric.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20type_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qoverload.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qswap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtresource.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttranslation.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstdlibdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcomparehelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtmetamacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstring.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qchar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpair.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydataops.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qxptype_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20functional.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q17memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlatin1stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qanystringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qutf8stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringtokenizer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter_base.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qeventloop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevicebase.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfloat16.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmath.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtformat_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterable.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetacontainer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtaggedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopeguard.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbindingstorage.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QString \
		../Qt/6.10.0/gcc_64/include/QtCore/QStringList \
		../Qt/6.10.0/gcc_64/include/QtCore/QMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata_impl.h \
		moc_predefs.h \
		../Qt/6.10.0/gcc_64/libexec/moc
	/home/mlayug/Qt/6.10.0/gcc_64/libexec/moc $(DEFINES) --include /home/mlayug/ElegantWeather/moc_predefs.h -I/home/mlayug/Qt/6.10.0/gcc_64/mkspecs/linux-g++ -I/home/mlayug/ElegantWeather -I/home/mlayug/Qt/6.10.0/gcc_64/include -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQuick -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtOpenGL -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtGui -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlMeta -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlModels -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlWorkerScript -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQml -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlIntegration -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtNetwork -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include weatherservice.h -o moc_weatherservice.cpp

moc_aiagent.cpp: aiagent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QObject \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversionchecks.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfiginclude.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconfig.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfigmacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreexports.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qassert.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtnoop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypes.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversion.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlogging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qflags.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qyieldcpu.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconstructormacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qexceptionhandling.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qforeach.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttypetraits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qminmax.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnumeric.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20type_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qoverload.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qswap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtresource.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttranslation.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstdlibdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcomparehelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtmetamacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstring.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qchar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpair.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydataops.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qxptype_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20functional.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q17memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlatin1stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qanystringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qutf8stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringtokenizer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter_base.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qeventloop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevicebase.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfloat16.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmath.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtformat_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterable.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetacontainer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtaggedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopeguard.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbindingstorage.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QProcess \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocess.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qspan.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20iterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QString \
		../Qt/6.10.0/gcc_64/include/QtCore/QStringList \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariantMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariantmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariant \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariant.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdebug.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qset.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhash.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q23utility.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20utility.h \
		moc_predefs.h \
		../Qt/6.10.0/gcc_64/libexec/moc
	/home/mlayug/Qt/6.10.0/gcc_64/libexec/moc $(DEFINES) --include /home/mlayug/ElegantWeather/moc_predefs.h -I/home/mlayug/Qt/6.10.0/gcc_64/mkspecs/linux-g++ -I/home/mlayug/ElegantWeather -I/home/mlayug/Qt/6.10.0/gcc_64/include -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQuick -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtOpenGL -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtGui -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlMeta -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlModels -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlWorkerScript -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQml -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtQmlIntegration -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtNetwork -I/home/mlayug/Qt/6.10.0/gcc_64/include/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include aiagent.h -o moc_aiagent.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../Qt/6.10.0/gcc_64/include/QtGui/QGuiApplication \
		../Qt/6.10.0/gcc_64/include/QtGui/qguiapplication.h \
		../Qt/6.10.0/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversionchecks.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfiginclude.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconfig.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfigmacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreexports.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qassert.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtnoop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypes.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversion.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlogging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qflags.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qyieldcpu.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconstructormacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qexceptionhandling.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qforeach.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttypetraits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qminmax.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnumeric.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20type_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qoverload.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qswap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtresource.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttranslation.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../Qt/6.10.0/gcc_64/include/QtGui/qtgui-config.h \
		../Qt/6.10.0/gcc_64/include/QtGui/qtguiexports.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstring.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qchar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstdlibdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcomparehelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtmetamacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpair.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydataops.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qxptype_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20functional.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q17memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlatin1stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qanystringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qutf8stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringtokenizer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter_base.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevicebase.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfloat16.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmath.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtformat_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterable.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetacontainer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtaggedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopeguard.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbindingstorage.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qeventloop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnativeinterface.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfuture.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfutureinterface.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmutex.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtsan_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qresultstore.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfuture_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qthreadpool.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qthread.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qrunnable.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qexception.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpromise.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariant.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdebug.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qset.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhash.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q23utility.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20utility.h \
		../Qt/6.10.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt/6.10.0/gcc_64/include/QtGui/qinputmethod.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlocale.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpoint.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcheckedint_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsize.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmargins.h \
		../Qt/6.10.0/gcc_64/include/QtGui/qguiapplication_platform.h \
		../Qt/6.10.0/gcc_64/include/QtQml/QQmlApplicationEngine \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlengine.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qurl.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qjsengine.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtimezone.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcalendar.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qjsvalue.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qtqmlglobal.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qtqml-config.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qtqmlexports.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qjsmanagedvalue.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qjsprimitivevalue.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qjsnumbercoercion.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmldebug.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqml.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlprivate.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmllist.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlparserstatus.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qversionnumber.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qspan.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20iterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtyperevision.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlregistration.h \
		../Qt/6.10.0/gcc_64/include/QtQmlIntegration/qqmlintegration.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlerror.h \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlabstracturlinterceptor.h \
		../Qt/6.10.0/gcc_64/include/QtQml/QQmlContext \
		../Qt/6.10.0/gcc_64/include/QtQml/qqmlcontext.h \
		weatherservice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QObject \
		../Qt/6.10.0/gcc_64/include/QtCore/QString \
		../Qt/6.10.0/gcc_64/include/QtCore/QStringList \
		../Qt/6.10.0/gcc_64/include/QtCore/QMap \
		aiagent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QProcess \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocess.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariantMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariantmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariant
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

weatherservice.o: weatherservice.cpp weatherservice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QObject \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversionchecks.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfiginclude.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconfig.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfigmacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreexports.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qassert.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtnoop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypes.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversion.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlogging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qflags.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qyieldcpu.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconstructormacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qexceptionhandling.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qforeach.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttypetraits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qminmax.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnumeric.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20type_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qoverload.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qswap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtresource.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttranslation.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstdlibdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcomparehelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtmetamacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstring.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qchar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpair.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydataops.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qxptype_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20functional.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q17memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlatin1stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qanystringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qutf8stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringtokenizer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter_base.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qeventloop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevicebase.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfloat16.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmath.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtformat_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterable.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetacontainer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtaggedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopeguard.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbindingstorage.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QString \
		../Qt/6.10.0/gcc_64/include/QtCore/QStringList \
		../Qt/6.10.0/gcc_64/include/QtCore/QMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QJsonDocument \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsondocument.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonparseerror.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcborvalue.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcborcommon.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcalendar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlocale.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariant.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdebug.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qset.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhash.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q23utility.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20utility.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qregularexpression.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qurl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/quuid.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qendian.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QJsonObject \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QJsonArray \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonarray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QUrlQuery \
		../Qt/6.10.0/gcc_64/include/QtCore/qurlquery.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QDateTime \
		../Qt/6.10.0/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qhttpheaders.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QSharedDataPointer \
		../Qt/6.10.0/gcc_64/include/QtCore/QUrl \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariant \
		../Qt/6.10.0/gcc_64/include/QtCore/q26numeric.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QList \
		../Qt/6.10.0/gcc_64/include/QtNetwork/QSslConfiguration \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qsslsocket.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qhostaddress.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qspan.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20iterator.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qsslerror.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcryptographichash.h \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qssl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QFlags \
		../Qt/6.10.0/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QMetaType \
		../Qt/6.10.0/gcc_64/include/QtNetwork/QNetworkReply \
		../Qt/6.10.0/gcc_64/include/QtNetwork/qnetworkreply.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QIODevice \
		../Qt/6.10.0/gcc_64/include/QtNetwork/QNetworkRequest \
		../Qt/6.10.0/gcc_64/include/QtCore/QSettings \
		../Qt/6.10.0/gcc_64/include/QtCore/qsettings.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QTimer \
		../Qt/6.10.0/gcc_64/include/QtCore/qtimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QLocale \
		../Qt/6.10.0/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o weatherservice.o weatherservice.cpp

aiagent.o: aiagent.cpp aiagent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QObject \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreglobal.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversionchecks.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfiginclude.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconfig.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtconfigmacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtcoreexports.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qassert.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtnoop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypes.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtversion.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlogging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qflags.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qyieldcpu.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qconstructormacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qexceptionhandling.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qforeach.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttypetraits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qminmax.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qnumeric.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20type_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qoverload.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qswap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtresource.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qttranslation.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcompare.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstdlibdetection.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcomparehelpers.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtmetamacros.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstring.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qchar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qpair.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qarraydataops.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qxptype_traits.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20functional.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q17memory.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearrayview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringfwd.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlatin1stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qanystringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qutf8stringview.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringtokenizer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringconverter_base.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qeventloop.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevicebase.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfloat16.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmath.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtformat_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiterable.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qmetacontainer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontainerinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtaggedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qscopeguard.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qbindingstorage.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QProcess \
		../Qt/6.10.0/gcc_64/include/QtCore/qprocess.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qspan.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20iterator.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QString \
		../Qt/6.10.0/gcc_64/include/QtCore/QStringList \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariantMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariantmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QMap \
		../Qt/6.10.0/gcc_64/include/QtCore/qmap.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qshareddata_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QVariant \
		../Qt/6.10.0/gcc_64/include/QtCore/qvariant.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdebug.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qset.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qhash.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qalloc.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q23utility.h \
		../Qt/6.10.0/gcc_64/include/QtCore/q20utility.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QJsonDocument \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsondocument.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonparseerror.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcborvalue.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcborcommon.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qcalendar.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qlocale.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qregularexpression.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qurl.h \
		../Qt/6.10.0/gcc_64/include/QtCore/quuid.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qendian.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QJsonObject \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QJsonArray \
		../Qt/6.10.0/gcc_64/include/QtCore/qjsonarray.h \
		../Qt/6.10.0/gcc_64/include/QtCore/QDebug \
		../Qt/6.10.0/gcc_64/include/QtCore/QDir \
		../Qt/6.10.0/gcc_64/include/QtCore/qdir.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qdirlisting.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfiledevice.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfile.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qfileinfo.h \
		../Qt/6.10.0/gcc_64/include/QtCore/qtimezone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aiagent.o aiagent.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_weatherservice.o: moc_weatherservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_weatherservice.o moc_weatherservice.cpp

moc_aiagent.o: moc_aiagent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aiagent.o moc_aiagent.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ElegantWeather/bin || mkdir -p $(INSTALL_ROOT)/opt/ElegantWeather/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ElegantWeather/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ElegantWeather/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ElegantWeather/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ElegantWeather/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

